name: Release Binary Assets
on:
  release:
    types:
      - published

env:
  BINARY_NAME: ssd-benchmark

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            binName: ${{ env.BINARY_NAME }}
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            binName: ${{ env.BINARY_NAME }}
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false
            binName: ${{ env.BINARY_NAME }}
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
            binName: ${{ env.BINARY_NAME }}.exe
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.cross }}
          args: --release --target=${{ matrix.target }}
      - name: Smoke Test
        uses: actions-rs/cargo@v1
        with:
          command: run
          use-cross: ${{ matrix.cross }}
          args: --release --target=${{ matrix.target }} -- -V
      - name: Create Archive
        id: archive
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          filename="${{ env.BINARY_NAME }}-$TAG-$TARGET.tar.gz"
          tar -czvf "$filename" README.md LICENSE -C "target/$TARGET/release" "${{ matrix.binName }}"
          echo "::set-output name=filename::$filename"
      - name: Upload Archive
        uses: ncipollo/release-action@v1.8.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ steps.archive.outputs.filename }}
          artifactContentType: application/octet-stream
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true

  pkg-deb:
    name: binary package .deb
    env:
      TARGET: x86_64-unknown-linux-musl
      TAG: ${{ github.event.release.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build .deb file
        uses: sassman/rust-deb-builder@v1
      - name: Archive deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}-${{ env.TAG }}-${{ env.TARGET }}.deb
          path: target/${{ env.TARGET }}/debian/${{ env.BINARY_NAME }}*.deb
      - name: upload deb file
        uses: ncipollo/release-action@v1.8.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: target/${{ env.TARGET }}/debian/${{ env.BINARY_NAME }}*.deb
          artifactContentType: application/octet-stream
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
